# Generated by Django 4.2.10 on 2024-03-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cooking_time', models.IntegerField(max_length=4)),
                ('difficulty', models.CharField(max_length=20)),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
